version: "2"

services:
    apache:
        image: "shedhost/apache"
        restart: always

        environment:
            APACHE_LOG_LEVEL: "${logging}"
            APACHE_DEFAULT_DOCROOT: "${docroot}"

        volumes:
            - ".:/var/shed/config"
            - "${sites}:/var/www"

        ports:
            - "${port}:80"

        links:
            - postgres
            - mysql
    postgres:
        image: "postgres:latest"
        restart: always

        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"

        volumes:
            - "${HOME}/.shed/data/postgres:/var/lib/postgresql/data/pgdata"
    mysql:
        image: "mysql:latest"
        restart: always

        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        volumes:
            - "${HOME}/.shed/data/mysql:/var/lib/mysql"
