version: "2"

services:
  apache:
    image: "shedhost/apache:latest"
    restart: unless-stopped

    environment:
      APACHE_UID: "${USER_ID}"
      APACHE_GID: "${GROUP_ID}"
      APACHE_LOG_LEVEL: "${logging}"
      APACHE_DEFAULT_DOCROOT: "${docroot}"

    volumes:
      - "./:/var/shed"
      - "./config/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./config/apache/php.ini:/usr/local/etc/php/php.ini"
      - "${sites}:/var/www"

    ports:
      - "${port}:80"

    links:
      - postgres
      - mysql
      - memcached
  npm:
    user: $USER_ID
    image: node:6.9.5
    volumes:
      - "./:/usr/src/app"
    working_dir: "/usr/src/app"
    command: "npm install"

  memcached:
    image: "memcached:1.4"
    restart: unless-stopped

  postgres:
    image: "postgres:9.6"
    restart: unless-stopped

    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - "${HOME}/.shed/data/postgres:/var/lib/postgresql/data/pgdata"

  mysql:
    image: "mysql:8.0"
    restart: unless-stopped

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    volumes:
      - "${HOME}/.shed/data/mysql:/var/lib/mysql"
