version: "2"

services:
    apache:
        build: "./apache"
        volumes:
            # Shed assumes that you want to use the parent folder of shed as
            # your docroot. If you do not, you should change .. below to be
            # something else. For example,
            #
            #     - "/home/kevin/Sites:/var/www"
            #
            - "..:/var/www"
        ports:
            # If you would like for your sites to be available on a different
            # port than port 80, change the first number here to something
            # else. For example,
            #
            #     - "8000:80"
            #
            - "80:80"
        links:
            - postgres
            - mysql
    postgres:
        image: "postgres:latest"
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - "./data/postgres:/var/lib/postgresql/data/pgdata"
    mysql:
        image: "mysql:latest"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "./data/mysql:/var/lib/mysql"
