version: "2"

services:
    apache:
        image: "shedhost/apache"
        restart: always

        environment:
            APACHE_LOG_LEVEL: "${APACHE_LOG_LEVEL}"
            APACHE_DEFAULT_DOCROOT: "${APACHE_DEFAULT_DOCROOT}"

        volumes:
            - ".:/var/shed/config"
            - "${APACHE_BASE_PATH}:/var/www"

        ports:
            - "${APACHE_PORT}:80"

        links:
            - postgres
            - mysql
    postgres:
        image: "postgres:latest"
        restart: always

        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"

        volumes:
            - "./data/postgres:/var/lib/postgresql/data/pgdata"
    mysql:
        image: "mysql:latest"
        restart: always

        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        volumes:
            - "./data/mysql:/var/lib/mysql"
