version: "2"

services:
    apache:
        image: "shedhost/apache"
        restart: unless-stopped

        environment:
            APACHE_LOG_LEVEL: "${logging}"
            APACHE_DEFAULT_DOCROOT: "${docroot}"

        volumes:
            - ".:/var/shed/config"
            - "${sites}:/var/www"

        ports:
            - "${port}:80"

        links:
            - postgres
            - mysql
            - memcached

    memcached:
        image: "memcached:1.4"
        restart: unless-stopped

    postgres:
        image: "postgres:9.6"
        restart: unless-stopped

        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"

        volumes:
            - "${HOME}/.shed/data/postgres:/var/lib/postgresql/data/pgdata"

    mysql:
        image: "mysql:8.0"
        restart: unless-stopped

        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        volumes:
            - "${HOME}/.shed/data/mysql:/var/lib/mysql"
