#!/bin/bash
cd $(dirname $0)

main() {

    while getopts ":d:e:h:s:w:" OPT; do
        case $OPT in
            d)
                DATABASE="$OPTARG"
                ;;
            e)
                ENV_ROOT="$OPTARG"
                ;;
            h)
                SERVER="$OPTARG"
                ;;
            s)
                SITE="$OPTARG"
                ;;
            w)
                WRITABLE="$OPTARG"
                ;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                exit 1
                ;;
        esac
    done

    shift $(($OPTIND - 1))

    if [ -n "$1" ]; then
        SITE="$1"
    fi

    if [ ! -v SITE ]; then
        echo "You must specify the site (-s) to fetch." >&2
        exit 1
    fi

    SERVER="${SERVER-$SITE}"
    DATABASE="${DATABASE-${SITE//[^a-zA-Z0-9-]/_}}"
    ENV_ROOT="${ENV_ROOT-/var/www/$SITE/dev}"
    WRITABLE="${WRITABLE-writable}"

    CONTAINER="$(docker-compose ps -q postgres)"

    ## Fetch Database
    echo ssh $SERVER pg_dump -cC $DATABASE -U postgres \| docker exec -i $CONTAINER psql -qU postgres
    ssh $SERVER pg_dump -cC $DATABASE -U postgres | docker exec -i $CONTAINER psql -qU postgres

    ## Fetch Files
    #echo scp -qr $SERVER:$ENV_ROOT/$WRITABLE $WRITABLE
    #scp -qr $SERVER:$ENV_ROOT/$WRITABLE $WRITABLE
}

main "$@"
