#!/bin/bash

##
# This fetches writable and database.
#

# These are used for shell colors.
B="\e[1m"
R="\e[0m"

# Change current directory to the directory of this script. This helps with
# docker-compose commands.
PROJECT_PWD="$(pwd -P)"
cd $(dirname $0)


main() {

    while getopts ":d:e:h:s:w:cn" OPT; do
        case $OPT in
            d)
                DATABASE="$OPTARG"
                ;;
            e)
                ENV_ROOT="$OPTARG"
                ;;
            h)
                SERVER="$OPTARG"
                ;;
            c)
                SHOW_CONFIG="1"
                ;;
            n)
                DRY_RUN="1"
                ;;
            s)
                SITE="$OPTARG"
                ;;
            w)
                WRITABLE="$OPTARG"
                ;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                exit 1
                ;;
        esac
    done

    shift $(($OPTIND - 1))

    if [ -n "$1" ]; then
        SITE="$1"
    fi

    WRITABLE="${WRITABLE-writable}"
    CONTAINER="$(docker-compose ps -q postgres)"

    if [ -z "$SERVER" ] && [ -n $SITE ]; then
        SERVER="$SITE"
    fi

    if [ -z "$ENV_ROOT" ] && [ -n "$SITE" ]; then
        ENV_ROOT="/var/www/$SITE/dev"
    fi

    if [ -z "$DATABASE" ] && [ -n "$SITE" ]; then
        DATABASE="dev_${SITE//[^-a-zA-Z0-9]/_}"
    fi

    if [ -z "$SERVER" ] || [ -z "$DATABASE" ] || [ -z "$WRITABLE" ] || [ -z "$ENV_ROOT" ]; then
        echo "Server, database, and writable are required."
    fi

    if [ -n "$SHOW_CONFIG" ]; then
        echo -e "Settings:"
        echo
        echo -e " - SERVER:    $B$SERVER$R"
        echo -e " - DATABASE:  $B$DATABASE$R"
        echo -e " - WRITABLE:  $B$ENV_ROOT/$WRITABLE$R"
        echo -e " - CONTAINER: $B${CONTAINER%"${CONTAINER#??????}"}$R"
        echo

        exit 0
    fi

    echo Fetching $DATABASE from $SERVER...
    ssh $SERVER pg_dump -cC $DATABASE -U postgres | docker exec -i $CONTAINER psql -qU postgres
    echo Done.

    echo
    echo Copying $ENV_ROOT/$WRITABLE from $SERVER to $PROJECT_PWD/$WRITABLE...
    scp -qr $SERVER:$ENV_ROOT/$WRITABLE $PROJECT_PWD/$WRITABLE
    echo Done.
}

main "$@"
