#!/bin/bash

cd $(dirname $0)

main() {
    case "$1" in
        up)
            docker-compose up -d
            ;;
        down)
            docker-compose down
            ;;
        *)
            echo "Usage: shed COMMAND"
            echo
            echo "Commands:"
            echo "  up    Starts shed."
            echo "  down  Stops shed."
            echo
    esac
}

main "$@"
