#!/usr/bin/env php
<?php

chdir(__DIR__);

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
}

$cmd = new Shed\Command(array_slice($argv, 1));
$cmd->run();
